# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "81b2b0c8aa59724c27df49dfe12bf394"
name = "ai_seo_chat"
application_url = "https://ai-seo-chat-3h2kkfv6w-touchstage-e448053b.vercel.app/"
embedded = true
handle = "ai_seo_chat"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "products/create", "products/update", "products/delete" ]
  uri = "/webhooks/products"

  # Metafield webhooks removed - not supported in current API version

  [[webhooks.subscriptions]]
  topics = [ "collections/create", "collections/update", "collections/delete" ]
  uri = "/webhooks/collections"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_content,write_content"

[auth]
redirect_urls = ["https://ai-seo-chat-3h2kkfv6w-touchstage-e448053b.vercel.app/auth/callback", "https://ai-seo-chat-3h2kkfv6w-touchstage-e448053b.vercel.app/auth/shopify/callback", "https://ai-seo-chat-3h2kkfv6w-touchstage-e448053b.vercel.app/api/auth/callback"]

[pos]
embedded = false

[app_proxy]
url = "https://ai-seo-chat-gk9lofw33-touchstage-e448053b.vercel.app/apps/ai-seo-chat"
prefix = "apps"
subpath = "ai-seo-chat"
