# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "81b2b0c8aa59724c27df49dfe12bf394"
name = "ai_seo_chat"
application_url = "https://partners.shopify.com/4469417/apps/276981317633"
embedded = true
handle = "ai_seo_chat"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_products,write_content,write_products"

[auth]
redirect_urls = [
  "https://partners.shopify.com/4469417/apps/276981317633/auth/callback",
  "https://partners.shopify.com/4469417/apps/276981317633/auth/shopify/callback",
  "https://partners.shopify.com/4469417/apps/276981317633/api/auth/callback"
]

[pos]
embedded = false
